### ISSUE TITLE
contacts between two move2 objects (rbind error)

### ISSUE THREAD

**Issue by raorben** [jedalong/wildlifeDI#5]
When I try running 

mca19 <- conProcess(traj, traj2, tc=15*60, dc=50, return = "contacts") 

or

mca19 <- conProcess(traj, traj2, tc=15*60, dc=50, return = "move2") 

I get the following error:
Error in rbind.data.frame(...) : 
  numbers of columns of arguments do not match

**Comment by jedalong** [comment]
if traj and traj2 have different columns e.g., different attibutes, i suspect this error will get thrown. I will look into an internal fix, but this is more a problem of data matching than a wildlifeDI problem per se. In the meantime try subsetting the columns of your input trajectories so that they are identical....

**Comment by jedalong** [comment]
see if the changes have fixed this issue, if so I will close it.

**Comment by jedalong** [comment]
note to self, probably worth creating an internal function for most of the intital work done in each analytical function to avoid duplicatiing code in each function.

**Comment by jedalong** [comment]
I have changed this and it now correctly uses mt_stack to combine two trajectories. This should be functional even if the columns do not agree between the two datasets. Thanks for raising this issue.
